name: mypy
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - appnope=0.1.0
  - astor=0.7.1
  - attrs=19.3.0
  - autopep8=1.5
  - backcall=0.1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - ca-certificates=2019.11.28
  - cctools=927.0.2
  - certifi=2019.11.28
  - cffi=1.13.2
  - clang=9.0.1
  - clang_osx-64=9.0.1
  - clangxx=9.0.1
  - clangxx_osx-64=9.0.1
  - compiler-rt=9.0.1
  - compiler-rt_osx-64=9.0.1
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fastcache=1.1.0
  - freetype=2.10.0
  - gast=0.2.2
  - gettext=0.19.8.1
  - gmp=6.2.0
  - gmpy2=2.1.0b1
  - google-pasta=0.1.8
  - graphviz=2.42.3
  - grpcio=1.23.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - icu=64.2
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - iteration_utilities=0.10.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.2
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld64=450.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.1
  - libffi=3.2.1
  - libflac=1.3.1
  - libgfortran=4.0.0
  - libgpuarray=0.7.6
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libogg=1.3.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsndfile=1.0.28
  - libsodium=1.0.17
  - libtiff=4.1.0
  - libvorbis=1.3.5
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=9.0.1
  - lxml=4.5.0
  - lz4-c=1.8.3
  - mako=1.1.0
  - markdown=3.2.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - more-itertools=8.2.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=6.0.3
  - numpy=1.18.1
  - openssl=1.1.1d
  - opt_einsum=3.1.0
  - pandas=1.0.1
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - patsy=0.5.1
  - pexpect=4.8.0
  - picklable-itertools=0.1.1
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.4
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pydocstyle=5.0.2
  - pydot=1.4.1
  - pygments=2.5.2
  - pygpu=0.7.6
  - pyparsing=2.4.6
  - pyrsistent=0.15.7
  - pysoundfile=0.10.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=18.1.1
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=45.2.0
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sqlite=3.30.1
  - statsmodels=0.11.0
  - sympy=1.5.1
  - tapi=1000.10.8
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - theano=1.0.4
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - wrapt=1.12.0
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.4.4
